# Generated by Django 5.0.14 on 2026-01-31 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Pflanzenname')),
                ('variety', models.CharField(blank=True, help_text='z.B. "Ochsenherz", "Cherry"', max_length=200, verbose_name='Sorte/Varietät')),
                ('seed_source', models.TextField(blank=True, help_text='Wo wurden die Samen gekauft oder gewonnen?', verbose_name='Samenherkunft')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Pflanze',
                'verbose_name_plural': 'Pflanzen',
                'ordering': ['name', 'variety'],
            },
        ),
        migrations.CreateModel(
            name='PlantingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Anbaujahr')),
                ('status', models.CharField(choices=[('planning', 'Planung'), ('sowing', 'Säen'), ('germinating', 'Keimung'), ('growing', 'Wachstum'), ('planted_out', 'Ausgepflanzt'), ('harvesting', 'Ernte'), ('finished', 'Abgeschlossen')], default='planning', max_length=20, verbose_name='Status')),
                ('seed_saved', models.BooleanField(default=False, help_text='Wurden Samen für das nächste Jahr gewonnen?', verbose_name='Samen gewonnen?')),
                ('seed_saved_notes', models.TextField(blank=True, verbose_name='Notizen zur Saatgutgewinnung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='plants.plant', verbose_name='Pflanze')),
            ],
            options={
                'verbose_name': 'Anbau-Zyklus',
                'verbose_name_plural': 'Anbau-Zyklen',
                'ordering': ['-year', 'plant__name'],
                'unique_together': {('plant', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sowing', 'Aussaat'), ('germination', 'Keimung'), ('transplanting', 'Umpflanzen'), ('watering', 'Gießen'), ('fertilizing', 'Düngen'), ('planting_out', 'Ins Beet pflanzen'), ('harvest', 'Ernte'), ('pruning', 'Schneiden'), ('other', 'Sonstiges')], max_length=20, verbose_name='Ereignistyp')),
                ('event_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('location', models.CharField(blank=True, help_text='z.B. "Topf 5cm", "Beet A", "Gewächshaus"', max_length=200, verbose_name='Ort')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Bei Bewässerung: Liter, bei Ernte: kg/Stück', max_digits=8, null=True, verbose_name='Menge')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('planting_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plants.plantingcycle', verbose_name='Anbau-Zyklus')),
            ],
            options={
                'verbose_name': 'Ereignis',
                'verbose_name_plural': 'Ereignisse',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10, verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('planting_cycle', models.ForeignKey(blank=True, help_text='Optional: Verknüpfung mit einem Anbau-Zyklus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plants.plantingcycle', verbose_name='Anbau-Zyklus')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['completed', '-priority', 'due_date'],
            },
        ),
    ]
